version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      development-dependencies:
        dependency-type: development
        patterns:
          - '*'
        exclude-patterns:
          - 'eslint'
          - 'eslint-config-react-app'
          - 'typescript'
          - '@typescript-eslint/*'
          - 'typescript-eslint'
      production-dependencies:
        dependency-type: production
        patterns:
          - '*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
